### ISSUE TITLE
How to create address offline?

### ISSUE THREAD

**Issue by Wangmmx** [bluzelle/curium#157]
Hello, I used the cosmos-sdk to generate the address offline:
1.From the private key through secp256k1 to generate the public key
2.And then through sha256 and ripemd160 to get the hashed result
3.Finally use bech32 to encode the prefix together
But The result obtained is different from the staking address in the wallet. What is wrong? The private keys of these two addresses are the same. I printed it out. And I also developed and supported some other currencies that use cosmos-sdk. Have not got this problem before.

Looking forward to your replay

**Comment by scottburch** [comment]
Not sure what you are trying to do, but can you provide the bech32 address?

**Comment by Wangmmx** [comment]
> Not sure what you are trying to do, but can you provide the bech32 address?

What do you mean bech32 address?
The  publickey is 035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d, and the address generated by offline method is bluzelle1c59l52a8a73fsfwa8gr3xnru7272xq38l54d4l, but the staking address on the website is bluzelle1t3wd6kzdwrw7pqkgh7ylhun4lafnjjeykvre6u

**Comment by Wangmmx** [comment]
I just want to create a bluzelle address offline, so I found the functions to create address, and use the cosmos-sdk as a reference, but got the different address from the website

**Comment by scottburch** [comment]
I have never tried to do it without the mnemonic, so I can't help.  If you have the mnemonic then the JS Client will do it.
bluzelle({mnemonic: mnemonic, endpoint: '', uuid: ''}).address

**Comment by Wangmmx** [comment]
If you use mnemonic words, it will also generate a public key. How to generate the public key to the address?

**Comment by scottburch** [comment]
We don't do that directly in the JS lib, so I don't have a public function for that.  That is done in the Cosmostation lib.  I pulled this code from the Cosmostation lib code.  Unfortunately, the pub key generating function is private.  But, here is the procedure they use.  Looks like this will put out a base64 encoded public key.

This is the path that we use.
cosmos.setPath("m/44\'/118\'/0\'/0/0")


```
Cosmos.prototype.getECPairPriv = function(mnemonic) {
	if (typeof mnemonic !== "string") {
	    throw new Error("mnemonic expects a string")
	}
	const seed = bip39.mnemonicToSeed(mnemonic);
	const node = bip32.fromSeed(seed);
	const child = node.derivePath(this.path);
	const ecpair = bitcoinjs.ECPair.fromPrivateKey(child.privateKey, {compressed : false})
	return ecpair.privateKey;
}
```
```
function getPubKeyBase64(ecpairPriv) {
	const pubKeyByte = secp256k1.publicKeyCreate(ecpairPriv);
	return Buffer.from(pubKeyByte, 'binary').toString('base64');
}

```

**Comment by Wangmmx** [comment]
Thanks for your reply!
If the PubKeyBase64 I get by your method is gSBVHVch6a6Ii81g33Bd51CdK8c9, how do I get the address next?

**Comment by scottburch** [comment]
You can get the hex by changing that 'base64' to 'hex' in the toString(), or whatever format you need it in
.  Here is the part of the code that calls getPubKeyBase64.  
```
		        "signatures": [
		            {
		                "signature": signatureBase64,
		                "account_number": stdSignMsg.json.account_number,
                		"sequence": stdSignMsg.json.sequence,
		                "pub_key": {
		                    "type": "tendermint/PubKeySecp256k1",
		                    "value": getPubKeyBase64(ecpairPriv)
		                }
		            }
		        ],
```

**Comment by Wangmmx** [comment]
I understand the signature here. I have already got the public key. I want to know what is the algorithm from the public key to the address? I used bech32 and bluzelle prefix to generate it. It doesn’t look right.

**Comment by scottburch** [comment]
Do you know that you can use blzcli to do this?

**Comment by scottburch** [comment]
blzcli keys add temp --recover (enter mnemonic when asked)
```
$ blzcli keys add temp
{
  "name": "temp",
  "type": "local",
  "address": "bluzelle1up8yvch288klvfalq3w33l25xsd2crpldn0q4w",
  "pubkey": "bluzellepub1addwnpepqtxqcdzfr9s8mjcvjrcz0lcq7d9uexn7e5kpgfytatl85x0985gaqzlzdpe",
  "mnemonic": "feed harbor apology breeze town client oxygen dismiss other click spin doll eye mercy increase parent pair patrol pen february leader kitchen reject sweet"
}
```

**Comment by scottburch** [comment]
Ok, I don't know how to go from public key to address.  I've never done that.

**Comment by Wangmmx** [comment]
The

> blzcli keys add temp --recover (enter mnemonic when asked)
> 
> ```
> $ blzcli keys add temp
> {
>   "name": "temp",
>   "type": "local",
>   "address": "bluzelle1up8yvch288klvfalq3w33l25xsd2crpldn0q4w",
>   "pubkey": "bluzellepub1addwnpepqtxqcdzfr9s8mjcvjrcz0lcq7d9uexn7e5kpgfytatl85x0985gaqzlzdpe",
>   "mnemonic": "feed harbor apology breeze town client oxygen dismiss other click spin doll eye mercy increase parent pair patrol pen february leader kitchen reject sweet"
> }
> ```

The pubKey is bluzellepub1addwnpepqtxqcdzfr9s8mjcvjrcz0lcq7d9uexn7e5kpgfytatl85x0985gaqzlzdpe? Why does it have a prefix? The pubKey I generated is different, I will try it again

**Comment by Wangmmx** [comment]
> Ok, I don't know how to go from public key to address. I've never done that.

I think there is something different from the pubKey, so the address is not match

**Comment by scottburch** [comment]
I guess I am missing what you want to do.  This is how you go from a mnemonic to a public address.  How to go from a public address to the bech32, I assume you can do that with a bech32 lib.
I have not done it myself.  So, I am not sure why it is not working for you.

**Comment by scottburch** [comment]
Here is the code for it from the cosmostation lib
	const seed = bip39.mnemonicToSeed(mnemonic);
	const node = bip32.fromSeed(seed);
	const child = node.derivePath(this.path);
	const words = bech32.toWords(child.identifier);
	return bech32.encode(this.bech32MainPrefix, words);

**Comment by Wangmmx** [comment]
> I guess I am missing what you want to do. This is how you go from a mnemonic to a public address. How to go from a public address to the bech32, I assume you can do that with a bech32 lib.
> I have not done it myself. So, I am not sure why it is not working for you.

Yes, I use the bech32 library. I have developed and generated COSMOS and several other currencies before, and they are all generated in this way, but BLZ is not the same, it seems that the public key is different

**Comment by scottburch** [comment]
Sorry, I have not been able to help.  I know that the JS lib works, so that code must be correct.  Let me know if you have any specific questions.  Or if you let me know what you are trying to do, maybe I can help.

**Comment by Wangmmx** [comment]
The pubkey by using cosmos-sdk is a hexadecimal number. The pubkey I generated is 035a27b3564c6a08337ba07f8120551d5721e9ae888bcd60df705de7509d2bc73d, instead of the bluzellepub1addwnpepqtxqcdzfr9x0985 in the example you gave me. Your pubkey must be handled. I just want to ask how it is processed ?

**Comment by Wangmmx** [comment]
If it is a normal cosmos-sdk, it will not be different. I have developed a lot of cosmos currencies, and have not encountered the problem of address generation errors. Now the addresses obtained through the public key are different. The key has a prefix, and the length is not the normal length of secp256k1, what exactly is done with the public key in Bluzelle
?

**Comment by Wangmmx** [comment]
Does the bluzelle account address in https://staking.bluzelle.com/account is the same privateKey as the erc20 token?, maybe it was not the same, I generated the correct address

**Comment by scottburch** [comment]
That is not my area.  I'm not sure how the mapping works from the ERC20 to Cosmos addresses

**Comment by Wangmmx** [comment]
Ok thanks for your patient reply！I will ask the wallet functions, where should I open the issue?

**Comment by scottburch** [comment]
I have put a question in our general chat to see if someone can help with a link to this issue.
