### ISSUE TITLE
Missing funds

### ISSUE THREAD

**Issue by cryptokj2** [bluzelle/curium#177]
I unstaked my BLZ 4 days ago and have not received my funds. 

bluzelle1rhz2l96wy9s7egklx8trn7ef7nc4tke9kw3q0q Send 14,792 BLZ to bluzelle1d3km2vdnhav6elv7yf3hn0d3u982eehv5ccjur

Any assistance is appreciated. 

Thanks

**Comment by scottburch** [comment]
@cryptokj2 The unstaking period is 21 days.

**Comment by cryptokj2** [comment]
The unstaking period has passed. I do not see my BLZ tokens. Can someone please assist? Thank you.
