### ISSUE TITLE
Unstaked - after 21 days - funds are missing? 

### ISSUE THREAD

**Issue by cryptokj2** [bluzelle/curium#180]
I unstaked my BLZ weeks ago and have not received my tokens. 

bluzelle1rhz2l96wy9s7egklx8trn7ef7nc4tke9kw3q0q Send 14,792 BLZ to bluzelle1d3km2vdnhav6elv7yf3hn0d3u982eehv5ccjur

The unstaking period of 21 days has passed. 

Can someone please assist? Thank you.

@cryptokj2

**Comment by scottburch** [comment]
Looking into it.  Sorry for the late reply.

**Comment by njmurarka** [comment]
We will need more details. Please send a DM to us in our Discord with the TX hash.

Also, please refrain from posting such issues here. This issue database is for code-related issues.

**Comment by cryptokj2** [comment]
I am not in Discord. The transaction information is included in the initial
post.

**Comment by njmurarka** [comment]
The TX hash. Is it included?

**Comment by cryptokj2** [comment]
I'm sorry, only the to and from addresses were in the initial issue post.
Here's the info:

B578262477C1A2AF8A13FF15295001E96691C1A7D3257B33E321EE1FEA11FF73

[image: image.png]

Thank you!

@cryptokj2

**Comment by cryptokj2** [comment]
In addition to the previous information, here's the transaction when I sent the BLZ over 80 days ago. 

0xe5ee8b05427675c8c69d45136f0e041f409dd57b386c47c2d62341d92cf6b785

If you need more information, let me know. I'm a bit concerned at this point. Thanks!

~@cryptokj2

**Comment by njmurarka** [comment]
Please check again. Your tokens should be back in your ETH wallet.

**Comment by cryptokj2** [comment]
Thank you so much. I really appreciate it. Many times when things like this
happen, the token holder gets no response, let alone any help.

Have a great day!

~ KJ
